
env = Environment(CXXFLAGS=["-std=c++11","-O2"])

env["CXX"] = "clang++"

env.Append(LINKFLAGS= ['-lpthread'])

env.Program("colourtoy", [ "Bitmap.cpp", 
                       "ColourPicker.cpp",
                       "ColourToy.cpp",
                       "lodepng.cpp",
                       "Version1.cpp",
                       "VersionFour.cpp",
                       "VersionThree.cpp",
                       "VersionTwo.cpp" ] )
