
env = Environment(CXXFLAGS=["-std=c++11","-O2"])

env.Program("colourtoy", [ "Bitmap.cpp", 
                       "ColourPicker.cpp",
                       "ColourToy.cpp",
                       "lodepng.cpp",
                       "Version1.cpp",
                       "VersionTwo.cpp" ] )
